version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    networks:
      -  selenoid
    ports:
      - "4444:4444"
    volumes:    
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
    environment:
      - "DOCKER_API_VERSION=1.35"
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    networks:
      -  selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
networks:
  selenoid:
   driver: bridge
